import React from 'react';
import { Alert, UserRole } from '../../types';
import { X, Download, Printer, ShieldCheck, FileText, AlertTriangle } from 'lucide-react';
import { useRole } from '../../context/RoleContext';

interface EvidenceModalProps {
  alert: Alert;
  onClose: () => void;
  onExportComplete?: () => void;
}

export const EvidenceModal: React.FC<EvidenceModalProps> = ({
  alert,
  onClose,
  onExportComplete,
}) => {
  const { roleConfig } = useRole();

  const mockSha256 = 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855'
    .split('')
    .map((c, i) => (i < 8 ? alert.id.charCodeAt(i % alert.id.length).toString(16) : c))
    .join('');

  const evidenceId = `EVD-GJ-2026-${alert.id.replace('ALT-', '')}`;

  const downloadJson = () => {
    const evidencePackage = {
      _NOTICE: 'SIMULATED EVIDENCE — DEMO ONLY — NOT REAL DATA — FOR PROPOSAL PRESENTATION',
      evidenceRecordId: evidenceId,
      incidentAlertId: alert.id,
      classification: 'SIMULATED / PROPOSAL DEMO',
      timestampUtc: new Date().toISOString(),
      issuingAuthority: 'Apex Unified Command Hub, Gujarat Police Concept',
      certifyingOfficer: roleConfig.title,
      officerBadge: roleConfig.badge,
      cryptographicSignature: {
        algorithm: 'SHA-256 / Ed25519 (Simulated)',
        payloadDigest: mockSha256,
        blockchainAnchorBlock: 84192,
      },
      incidentDetails: {
        type: alert.type,
        confidence: `${alert.confidence}%`,
        location: alert.locationName,
        district: alert.district,
        cameraId: alert.cameraId,
        eventMetadata: alert.details,
      },
      auditLifecycle: alert.timeline,
      legalDisclaimer:
        'This dossier was generated by the Apex prototype demonstration platform. All vehicle registration numbers, facial identity markers, coordinates, and timestamps are synthetic and illustrative.',
    };

    const dataStr = 'data:text/json;charset=utf-8,' + encodeURIComponent(JSON.stringify(evidencePackage, null, 2));
    const downloadAnchor = document.createElement('a');
    downloadAnchor.setAttribute('href', dataStr);
    downloadAnchor.setAttribute('download', `${evidenceId}_SIMULATED_PACKAGE.json`);
    document.body.appendChild(downloadAnchor);
    downloadAnchor.click();
    downloadAnchor.remove();

    if (onExportComplete) onExportComplete();
  };

  const handlePrint = () => {
    window.print();
    if (onExportComplete) onExportComplete();
  };

  return (
    <div className="fixed inset-0 z-50 bg-black/80 backdrop-blur-sm flex items-center justify-center p-4 overflow-y-auto">
      <div className="bg-slate-900 border border-slate-700 rounded-2xl w-full max-w-2xl overflow-hidden shadow-2xl relative my-8">
        {/* Top Watermark Stripe */}
        <div className="bg-rose-950 text-rose-300 border-b border-rose-800/80 px-4 py-2 text-center font-mono text-xs font-bold tracking-widest uppercase flex items-center justify-center space-x-2">
          <AlertTriangle className="w-4 h-4 text-rose-400" />
          <span>SIMULATED EVIDENCE — DEMO ONLY — FOR PROPOSAL PRESENTATION</span>
        </div>

        {/* Header */}
        <div className="p-5 border-b border-slate-800 flex items-center justify-between">
          <div className="flex items-center space-x-3">
            <div className="p-2.5 rounded-xl bg-blue-950/60 border border-blue-800 text-blue-400">
              <FileText className="w-6 h-6" />
            </div>
            <div>
              <h2 className="text-base font-bold text-white">Forensic Evidence Package</h2>
              <div className="text-xs font-mono text-slate-400">Record ID: {evidenceId}</div>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-1.5 rounded-lg hover:bg-slate-800 text-slate-400 hover:text-white transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Content Body */}
        <div className="p-5 space-y-4 max-h-[60vh] overflow-y-auto font-sans text-xs">
          {/* Certificate Metadata Card */}
          <div className="bg-slate-950/80 border border-slate-800 rounded-xl p-4 space-y-3">
            <div className="flex items-center justify-between border-b border-slate-800 pb-2">
              <span className="text-slate-400 uppercase font-mono text-[10px] tracking-wider">
                Jurisdiction & Authority
              </span>
              <span className="bg-emerald-950 text-emerald-300 border border-emerald-800/80 px-2 py-0.5 rounded font-mono text-[10px] flex items-center space-x-1">
                <ShieldCheck className="w-3 h-3" />
                <span>Simulated Sec. 65B Certified</span>
              </span>
            </div>

            <div className="grid grid-cols-2 gap-3 text-slate-300 font-mono">
              <div>
                <span className="text-slate-500 block text-[10px]">ISSUING AUTHORITY</span>
                <strong>Apex State Command Hub</strong>
              </div>
              <div>
                <span className="text-slate-500 block text-[10px]">CERTIFYING OFFICER</span>
                <strong>{roleConfig.title} ({roleConfig.badge})</strong>
              </div>
              <div>
                <span className="text-slate-500 block text-[10px]">ORIGIN SENSOR</span>
                <strong>{alert.cameraId} ({alert.district})</strong>
              </div>
              <div>
                <span className="text-slate-500 block text-[10px]">INCIDENT TIMESTAMP</span>
                <strong>2026-09-14 {alert.timestamp} IST</strong>
              </div>
            </div>
          </div>

          {/* Cryptographic Proof Card */}
          <div className="bg-slate-950/80 border border-slate-800 rounded-xl p-4 space-y-2 font-mono">
            <div className="text-slate-400 text-[10px] uppercase tracking-wider">
              Cryptographic Immutability Digest (SHA-256)
            </div>
            <div className="bg-slate-900 border border-slate-800 p-2.5 rounded text-[11px] text-emerald-400 break-all select-all font-mono">
              {mockSha256}
            </div>
            <div className="text-[10px] text-slate-500">
              Anchored into Gujarat Police Concept Tamper-Proof Audit Chain (Block #84192)
            </div>
          </div>

          {/* Incident Event Breakdown */}
          <div className="space-y-2">
            <div className="text-slate-400 font-mono text-[10px] uppercase tracking-wider">
              Target & Incident Metadata
            </div>
            <div className="bg-slate-950/80 border border-slate-800 rounded-xl p-3 space-y-1.5 font-mono text-[11px]">
              <div className="flex justify-between">
                <span className="text-slate-500">Alert Type:</span>
                <span className="text-white font-semibold">{alert.type}</span>
              </div>
              <div className="flex justify-between">
                <span className="text-slate-500">Classification Confidence:</span>
                <span className="text-blue-400">{alert.confidence}% (Synthetic Score)</span>
              </div>
              <div className="flex justify-between">
                <span className="text-slate-500">Location Point:</span>
                <span className="text-slate-300">{alert.locationName}</span>
              </div>
              {alert.details.plateNumber && (
                <div className="flex justify-between">
                  <span className="text-slate-500">Flagged Plate:</span>
                  <span className="text-amber-400">{alert.details.plateNumber}</span>
                </div>
              )}
              {alert.details.targetId && (
                <div className="flex justify-between">
                  <span className="text-slate-500">Target ID:</span>
                  <span className="text-rose-400">{alert.details.targetId}</span>
                </div>
              )}
              {alert.details.notes && (
                <div className="pt-2 border-t border-slate-800 text-slate-400 text-[10px] font-sans">
                  {alert.details.notes}
                </div>
              )}
            </div>
          </div>

          {/* Mandatory Watermark Notice */}
          <div className="p-3 bg-amber-950/40 border border-amber-800/60 rounded-xl text-[10px] text-amber-300 font-mono">
            <strong>GOVERNANCE NOTICE:</strong> This evidentiary artifact is a conceptual simulation generated for stakeholder demonstration. Production deployment requires certification under Section 65B of the Indian Evidence Act, verified chain-of-custody logging, and DPDP Act 2023 compliance auditing.
          </div>
        </div>

        {/* Footer Actions */}
        <div className="p-4 bg-slate-950 border-t border-slate-800 flex items-center justify-between">
          <button
            onClick={onClose}
            className="px-4 py-2 rounded-lg text-white hover:text-slate-200 font-bold text-xs hover:bg-slate-900 transition-colors"
          >
            Cancel
          </button>

          <div className="flex items-center space-x-2">
            <button
              onClick={handlePrint}
              className="px-3.5 py-2 rounded-lg bg-slate-800 hover:bg-slate-700 text-white font-bold text-xs flex items-center space-x-1.5 transition-colors"
            >
              <Printer className="w-3.5 h-3.5" />
              <span>Print Dossier</span>
            </button>

            <button
              onClick={downloadJson}
              className="px-4 py-2 rounded-lg bg-blue-600 hover:bg-blue-500 text-white font-bold text-xs flex items-center space-x-1.5 shadow-lg transition-colors"
            >
              <Download className="w-3.5 h-3.5" />
              <span>Download Evidence Package (.json)</span>
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
